package example.enums;

/**
 * 決定性有限オートマトン(Deterministic Finite Automaton, DFA)
 * <p>Html 文字列の状態</p>
 */
public enum DfaState {
    Initial,
    ClosingTag,
    ClosingTag_1,
    ClosingSelf,
    Element,
    Attribute,
    Value,
    InnerText,
    CssContent,
    CssClosing_1,
    CssClosing_2,
    CssClosing_3,
    CssClosing_4,
    CssClosing_5,
    CssClosing_6,
    CssClosing_7,
    JsContent,
    JsClosing_1,
    JsClosing_2,
    JsClosing_3,
    JsClosing_4,
    JsClosing_5,
    JsClosing_6,
    JsClosing_7,
    JsClosing_8,
    Document,
    Document_1,
    Document_2,
    Document_3,
    Document_4,
    Document_5,
    Document_6,
    Document_7,
    Document_8,
    Document_9,
    CommentContent,
    Comment_1,
    Comment_2,
    Comment_3,
    Comment_4,
    CommentClosing_1,
    CommentClosing_2,
    SingleQuotation,
    DoubleQuotation,
    UnknownItem,
}
